
services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ilike2pizza
      MYSQL_DATABASE: task_application
      MYSQL_USER: root
      MYSQL_PASSWORD: Ilike2pizza@
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: springapi
    build: Dockerfile
    container_name: spring-api
    depends_on:
      - mysql
    ports:
      - "8000:8080"

volumes:
  mysql_data: